[project]
name = "airope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat>=0.4.5",
    "autogen-ext[openai]>=0.4.5",
    "black>=24.10.0",
    "uv>=0.5.26",
]
